### ISSUE TITLE
Pre V1 Features To-Do

### ISSUE THREAD

**Issue by bencbernstein** [bencbernstein/Track-Your-Reps#71]
- [x]  Date Library - O
- [x] Scroll View - O
- [ ] Add missing information - O
- [x] Data Clean - Refactor - B
- [x] Event Summary Refactor / Layout - B
- [ ] First documentation pass - O
- [ ] Turn off horizontal view - O
- [ ] Rename repo to InstaGov - O
